name: Build & Release Docker Image to Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: andronics/vpn-proxy

jobs:
  
  build-and-release:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Container Registry Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Metadata Extraction
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Image Version
        run: echo "IMAGE_VERSION=$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_ENV"
      
      - name: Build & Push Docker Image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}